#!/usr/bin/env tsx
// [self-platform] F9+F16 M4: render a project's stored GoTrue config into a
// docker-compose override and restart the target GoTrue container.
//
// GoTrue reads env at boot, so this is how stored config becomes LIVE. On a
// shared stack the target GoTrue serves every project → applying any ref is
// stack-scoped. Studio never runs this; an operator does (like register-project).
//
// SECURITY: the rendered override file contains DECRYPTED secrets (GOTRUE_*_SECRET,
// GOTRUE_SMTP_PASS). It is gitignored + must be chmod 600. Never commit it.
import { execFileSync } from 'node:child_process'
import { chmodSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import crypto from 'crypto-js'

// The docker-compose SERVICE KEY (docker/docker-compose.yml `auth:`), NOT the
// container_name `supabase-auth` — `docker compose up -d`/-f merging resolve by service key.
const DEFAULT_AUTH_SERVICE = 'auth'

// Field names GoTrue reads under a different env name than GOTRUE_<field>.
// Empty today (the contract field names ARE the GoTrue env names sans prefix);
// add an entry only if a live field is proven to disagree.
const ENV_NAME_OVERRIDES: Record<string, string> = {}

// Response-only / computed fields that must never be applied.
const READONLY_FIELDS = new Set([
  'MAILER_SUBJECTS_CUSTOM_CONTENTS',
  'MAILER_TEMPLATES_CUSTOM_CONTENTS',
  'CUSTOM_OAUTH_MAX_PROVIDERS',
])

function decryptSecret(
  ciphertext: string,
  key = process.env.PLATFORM_ENCRYPTION_KEY || ''
): string {
  if (!key) throw new Error('PLATFORM_ENCRYPTION_KEY is not set')
  const out = crypto.AES.decrypt(ciphertext, key).toString(crypto.enc.Utf8)
  if (!out) throw new Error('failed to decrypt platform secret')
  return out
}

export function parseArgs(argv: string[]): { ref?: string; target?: string; dryRun: boolean } {
  let ref: string | undefined
  let target: string | undefined
  let dryRun = false
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (a === '--dry-run') dryRun = true
    else if (a === '--target') target = argv[++i]
    else if (!a.startsWith('--') && ref === undefined) ref = a
  }
  return { ref, target, dryRun }
}

function formatValue(value: unknown): string | undefined {
  if (value === null || value === undefined) return undefined
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  if (typeof value === 'number') return String(value)
  if (Array.isArray(value)) return value.join(',')
  if (typeof value === 'object') return undefined // arrays handled above; skip plain objects
  return String(value)
}

// effective = { ...stored.config, ...decrypted secrets } — real overrides only.
export function renderGotrueEnv(effective: Record<string, unknown>): Record<string, string> {
  const env: Record<string, string> = {}
  for (const [field, value] of Object.entries(effective)) {
    // [self-platform] M4 review C1: backstop for rows written before the
    // upsertConfig whitelist (or via manual psql) — a malicious/malformed
    // field name could otherwise dedent out of the compose environment block.
    if (!/^[A-Z][A-Z0-9_]*$/.test(field)) continue
    if (READONLY_FIELDS.has(field)) continue
    const formatted = formatValue(value)
    if (formatted === undefined) continue
    env[ENV_NAME_OVERRIDES[field] ?? `GOTRUE_${field}`] = formatted
  }
  return env
}

// Replace the values of secret-sourced env vars with a mask for safe preview.
export function maskSecretValues(
  env: Record<string, string>,
  secretEnvNames: Set<string>
): Record<string, string> {
  const out: Record<string, string> = {}
  for (const [k, v] of Object.entries(env)) out[k] = secretEnvNames.has(k) ? '******' : v
  return out
}

export function toComposeOverrideYaml(service: string, env: Record<string, string>): string {
  const lines = [
    '# [self-platform] M4 GENERATED by apply-auth-config — DO NOT COMMIT (contains plaintext secrets).',
    'services:',
    `  ${service}:`,
    '    environment:',
  ]
  for (const [k, v] of Object.entries(env)) {
    lines.push(`      ${k}: ${JSON.stringify(v)}`)
  }
  return lines.join('\n') + '\n'
}

// Reads config+secrets for a ref from platform-db via `docker exec psql`. Uses
// plain single-quote-escaped literal interpolation (mirrors register-project.ts's
// DEREGISTER branch, not its PREPARE/EXECUTE `psql()` helper) — adequate here since
// `ref` is operator-supplied, not user/LLM-controlled input.
function loadStored(ref: string): {
  config: Record<string, unknown>
  secrets: Record<string, string>
} {
  const container = process.env.PLATFORM_DB_CONTAINER || 'supabase-platform-db'
  const literal = `'${ref.replace(/'/g, "''")}'`
  const sql = `select coalesce(json_build_object('config', config, 'secrets', secrets)::text, '') from platform.auth_config where project_ref = ${literal};`
  const out = execFileSync(
    'docker',
    [
      'exec',
      '-i',
      container,
      'psql',
      '-U',
      'postgres',
      '-d',
      'platform',
      '-t',
      '-A',
      '-v',
      'ON_ERROR_STOP=1',
    ],
    { input: sql + '\n', encoding: 'utf8' }
  ).trim()
  if (!out) return { config: {}, secrets: {} }
  return JSON.parse(out)
}

export function main(argv = process.argv.slice(2)) {
  const { ref, target, dryRun } = parseArgs(argv)
  if (!ref) throw new Error('usage: apply-auth-config <ref> [--target <container>] [--dry-run]')
  const service = target || process.env.PLATFORM_AUTH_CONTAINER || DEFAULT_AUTH_SERVICE

  const stored = loadStored(ref)
  const decrypted: Record<string, string> = {}
  for (const [k, v] of Object.entries(stored.secrets)) decrypted[k] = decryptSecret(v)
  const env = renderGotrueEnv({ ...stored.config, ...decrypted })

  if (dryRun) {
    const secretEnvNames = new Set(
      Object.keys(stored.secrets).map((k) => ENV_NAME_OVERRIDES[k] ?? `GOTRUE_${k}`)
    )
    const maskedYaml = toComposeOverrideYaml(service, maskSecretValues(env, secretEnvNames))
    process.stdout.write(maskedYaml)
    process.stdout.write(
      `\n# dry-run: would restart ${service} with ${Object.keys(env).length} GOTRUE_* vars\n`
    )
    return
  }

  const yaml = toComposeOverrideYaml(service, env)
  const composeDir =
    process.env.PLATFORM_COMPOSE_DIR || path.resolve(__dirname, '../../..', 'docker')
  const overridePath = path.join(composeDir, 'docker-compose.auth-override.yml')
  writeFileSync(overridePath, yaml, { mode: 0o600 })
  chmodSync(overridePath, 0o600)
  process.stderr.write(
    `[apply-auth-config] wrote ${overridePath} (contains PLAINTEXT secrets — chmod 600, never commit)\n`
  )
  execFileSync(
    'docker',
    [
      'compose',
      '-f',
      'docker-compose.yml',
      '-f',
      'docker-compose.auth-override.yml',
      'up',
      '-d',
      service,
    ],
    { cwd: composeDir, stdio: 'inherit' }
  )
  process.stdout.write(`[apply-auth-config] applied ${ref} → restarted ${service} (stack-scoped)\n`)
}

// tsx entrypoint
if (process.argv[1] && process.argv[1].endsWith('apply-auth-config.ts')) {
  main()
}
