image:
  repository: ghcr.io/supabase/backup-operator
  tag: v0.1.1
  digest: ""
replicaCount: 1
serviceAccount:
  create: true
  name: backup-operator
service:
  port: 8080
serviceAssertion:
  existingSecret: backup-operator-secrets
  key: service-assertion-key
persistence:
  create: true
  existingClaim: ""
  storageClass: ""
  size: 10Gi
