apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-operator-cloudnativepg
  namespace: supabase
rules:
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["clusters", "backups"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["barmancloud.cnpg.io"]
    resources: ["objectstores"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "endpoints", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-operator-cloudnativepg
  namespace: supabase
subjects:
  - kind: ServiceAccount
    name: backup-operator
    namespace: supabase
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backup-operator-cloudnativepg
