ALTER TABLE operations ADD COLUMN IF NOT EXISTS desired_revision TEXT NOT NULL DEFAULT '';
ALTER TABLE operations ADD COLUMN IF NOT EXISTS desired_digest TEXT NOT NULL DEFAULT '';
ALTER TABLE operations ADD COLUMN IF NOT EXISTS snapshot_canonical TEXT NOT NULL DEFAULT '{}';
