// [self-platform] Renders stored Auth settings into the Compose override that
// makes them live. GoTrue reads its configuration from the environment at
// boot, so the only way to change a running Auth service is to recreate it
// with new environment values. A Compose override is used because
// `environment:` entries in the upstream Compose file win over `env_file`.
//
// Pure module with no Studio imports: docker/scripts/platform/apply-auth-config.ts
// uses the same rules.

// Field names GoTrue reads under a different env name than GOTRUE_<field>.
// Empty today: the contract field names are the GoTrue env names without the
// prefix. Add an entry only when a live field is proven to disagree.
export const AUTH_ENV_NAME_OVERRIDES: Readonly<Record<string, string>> = {}

// Response-only or computed fields that must never be applied.
export const AUTH_READONLY_FIELDS: ReadonlySet<string> = new Set([
  'MAILER_SUBJECTS_CUSTOM_CONTENTS',
  'MAILER_TEMPLATES_CUSTOM_CONTENTS',
  'CUSTOM_OAUTH_MAX_PROVIDERS',
])

const FIELD_NAME_PATTERN = /^[A-Z][A-Z0-9_]*$/
// Any environment variable name; safe as a plain YAML key.
const ENV_NAME_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/

export function authEnvName(field: string): string {
  return AUTH_ENV_NAME_OVERRIDES[field] ?? `GOTRUE_${field}`
}

export function formatAuthEnvValue(value: unknown): string | undefined {
  if (value === null || value === undefined) return undefined
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : undefined
  if (Array.isArray(value)) return value.join(',')
  if (typeof value === 'object') return undefined
  return String(value)
}

/**
 * Renders only the fields present in `stored`, which holds the operator's
 * explicit overrides. Fields that come only from Studio's defaults are left to
 * the base Compose environment.
 */
export function renderGotrueEnv(stored: Record<string, unknown>): Record<string, string> {
  const env: Record<string, string> = {}
  for (const [field, value] of Object.entries(stored)) {
    // A malformed field name could otherwise break out of the environment block.
    if (!FIELD_NAME_PATTERN.test(field)) continue
    if (AUTH_READONLY_FIELDS.has(field)) continue
    const formatted = formatAuthEnvValue(value)
    if (formatted === undefined) continue
    env[authEnvName(field)] = formatted
  }
  return env
}

/**
 * Compose interpolates `$` in Compose files, so a literal `$` must be written
 * as `$$`. JSON string syntax is valid YAML and handles quotes, newlines, and
 * other special characters.
 */
export function composeYamlString(value: string): string {
  return JSON.stringify(value.replaceAll('$', '$$$$'))
}

export function toComposeOverrideYaml(
  service: string,
  env: Record<string, string>,
  header = '# Generated by Fleet from the project Auth settings. Do not edit.'
): string {
  if (!/^[a-z][a-z0-9-]{0,62}$/.test(service)) throw new Error('Invalid Compose service name')
  const lines = [header, 'services:', `  ${service}:`]
  const entries = Object.entries(env).sort(([left], [right]) => left.localeCompare(right))
  if (entries.length === 0) {
    lines.push('    environment: {}')
  } else {
    lines.push('    environment:')
    for (const [name, value] of entries) {
      if (!ENV_NAME_PATTERN.test(name)) throw new Error(`Invalid environment name ${name}`)
      lines.push(`      ${name}: ${composeYamlString(value)}`)
    }
  }
  return lines.join('\n') + '\n'
}

export type AuthRuntimeApplyPlan = {
  /** Compose override content for the `auth` service. */
  content: string
  /** Stored non-secret fields that the override applies, sorted. */
  appliedFields: string[]
  /** Stored secret fields that this apply cannot deliver, sorted. */
  skippedSecretFields: string[]
}

/**
 * Plans an apply from the stored non-secret settings. Secrets are never
 * rendered: the override travels through the operation record, which is not
 * a secret channel.
 */
export function planAuthRuntimeApply(input: {
  /** Stored non-secret overrides. */
  config: Record<string, unknown>
  /** Names of the stored secret overrides. */
  storedSecretFields: Iterable<string>
  /** Every field treated as a secret, used to keep secrets out of `config`. */
  secretFieldNames: ReadonlySet<string>
  service?: string
}): AuthRuntimeApplyPlan {
  const nonSecret = Object.fromEntries(
    Object.entries(input.config).filter(([field]) => !input.secretFieldNames.has(field))
  )
  const env = renderGotrueEnv(nonSecret)
  const appliedFields = Object.keys(nonSecret)
    .filter((field) => env[authEnvName(field)] !== undefined)
    .sort()
  return {
    content: toComposeOverrideYaml(input.service ?? 'auth', env),
    appliedFields,
    skippedSecretFields: [...new Set(input.storedSecretFields)].sort(),
  }
}

/**
 * Renders decrypted secret overrides into the Compose override that Studio
 * seals to the Fleet Agent. Only for sealing; never store or log the result.
 */
export function renderAuthSecretsOverride(secrets: Record<string, string>): string {
  return toComposeOverrideYaml(
    'auth',
    renderGotrueEnv(secrets),
    '# Generated by Fleet from the project Auth secrets. Do not edit.'
  )
}
