// [self-platform] Phase 2: apply stored Auth settings to a Fleet-managed stack.
//
// Non-secret overrides go to `compose.yml` for the `auth` service; stored
// secrets go to `secrets.compose.yml`, sealed to the Fleet Agent. See
// service-config-apply.ts for the apply mechanics. On Kubernetes both are
// sealed into one Secret.
import { readStoredAuthOverrides, readStoredAuthSecrets, SECRET_FIELDS } from './auth-config'
import { planAuthRuntimeApply, renderGotrueEnv } from './auth-runtime'
import {
  commitServiceConfigApply,
  loadServiceConfigApplyPlan,
  type ApplyRequest,
  type ServiceConfigApplyAvailability,
  type ServiceConfigApplyOperation,
  type ServiceConfigApplyState,
  type ServiceConfigSpec,
} from './service-config-apply'

export const AUTH_CONFIG_DOMAIN = 'auth'
const OVERRIDE_PATH = 'compose.yml'
const AUTH_SPEC: ServiceConfigSpec = {
  domain: AUTH_CONFIG_DOMAIN,
  service: 'auth',
  label: 'Auth settings',
  secretsHeader: '# Generated by Fleet from the project Auth secrets. Do not edit.',
  // docker/k8s/single-project/11-core.yaml reads configurable GOTRUE_*
  // settings with envFrom, the Fleet Secret last, so delivered values win.
  supportsKubernetes: true,
}

export type AuthApplyStatus = {
  availability: ServiceConfigApplyAvailability
  state: ServiceConfigApplyState
  isOwnedByFleet: boolean
  appliedFields: string[]
  /** Stored secret fields delivered sealed to the Fleet Agent, sorted. */
  sealedSecretFields: string[]
  /** Stored secret fields that cannot be delivered, sorted. */
  skippedSecretFields: string[]
  expectedGeneration: number
  operation: ServiceConfigApplyOperation | null
}

async function loadAuthApplyPlan(projectRef: string, request: ApplyRequest, isStrict: boolean) {
  const [overrides, secrets] = await Promise.all([
    readStoredAuthOverrides(projectRef),
    readStoredAuthSecrets(projectRef),
  ])
  const plan = planAuthRuntimeApply({
    config: overrides.config,
    storedSecretFields: overrides.secretFields,
    secretFieldNames: SECRET_FIELDS,
  })
  const secretsEnv = renderGotrueEnv(secrets)
  const applyPlan = await loadServiceConfigApplyPlan({
    spec: AUTH_SPEC,
    projectRef,
    request,
    isStrict,
    plainFiles: [{ path: OVERRIDE_PATH, content: plan.content }],
    plainEnv: plan.env,
    secretsEnv: Object.keys(secretsEnv).length > 0 ? secretsEnv : null,
    hasPlainSettings: plan.appliedFields.length > 0,
  })
  const status: AuthApplyStatus = {
    availability: applyPlan.availability,
    state: applyPlan.state,
    isOwnedByFleet: applyPlan.isOwnedByFleet,
    appliedFields: plan.appliedFields,
    sealedSecretFields: applyPlan.areSecretsSealed ? plan.skippedSecretFields : [],
    skippedSecretFields: applyPlan.areSecretsSealed ? [] : plan.skippedSecretFields,
    expectedGeneration: applyPlan.expectedGeneration,
    operation: applyPlan.operation,
  }
  return { applyPlan, status }
}

export async function getAuthApplyStatus(
  projectRef: string,
  request: ApplyRequest
): Promise<AuthApplyStatus> {
  return (await loadAuthApplyPlan(projectRef, request, false)).status
}

export async function applyAuthConfig(input: {
  projectRef: string
  expectedGeneration: number
  confirmOwnership: boolean
  idempotencyKey: string
  actor: string
  correlationId: string
  aal?: string
  aalAuthenticatedAt?: number
}) {
  const { applyPlan } = await loadAuthApplyPlan(
    input.projectRef,
    { actor: input.actor, correlationId: input.correlationId },
    true
  )
  return commitServiceConfigApply(applyPlan, input)
}
