import { describe, expect, it } from 'vitest'

import {
  composeYamlString,
  planAuthRuntimeApply,
  renderGotrueEnv,
  toComposeOverrideYaml,
} from './auth-runtime'

describe('renderGotrueEnv', () => {
  it('maps stored fields to GOTRUE_ names and formats values', () => {
    expect(
      renderGotrueEnv({
        SITE_URL: 'https://app.example.test',
        DISABLE_SIGNUP: true,
        JWT_EXP: 7200,
        URI_ALLOW_LIST: ['https://a.test', 'https://b.test'],
        SMS_PROVIDER: null,
      })
    ).toEqual({
      GOTRUE_SITE_URL: 'https://app.example.test',
      GOTRUE_DISABLE_SIGNUP: 'true',
      GOTRUE_JWT_EXP: '7200',
      GOTRUE_URI_ALLOW_LIST: 'https://a.test,https://b.test',
    })
  })

  it('skips read-only fields, objects, and malformed names', () => {
    expect(
      renderGotrueEnv({
        MAILER_TEMPLATES_CUSTOM_CONTENTS: { invite: true },
        CUSTOM_OAUTH_MAX_PROVIDERS: 5,
        'X: 1\nservices': 'bad',
        lower_case: 'bad',
        JWT_EXP: Number.NaN,
      })
    ).toEqual({})
  })
})

describe('toComposeOverrideYaml', () => {
  it('escapes Compose interpolation and quotes every value', () => {
    expect(composeYamlString('pa$word ${HOME} "quoted"\nline')).toBe(
      '"pa$$word $${HOME} \\"quoted\\"\\nline"'
    )
    const yaml = toComposeOverrideYaml('auth', {
      GOTRUE_SITE_URL: 'https://x.test',
      GOTRUE_A: '$1',
    })
    expect(yaml).toBe(
      [
        '# Generated by Fleet from the project Auth settings. Do not edit.',
        'services:',
        '  auth:',
        '    environment:',
        '      GOTRUE_A: "$$1"',
        '      GOTRUE_SITE_URL: "https://x.test"',
        '',
      ].join('\n')
    )
  })

  it('writes an empty environment when nothing is stored', () => {
    expect(toComposeOverrideYaml('auth', {})).toContain('    environment: {}\n')
  })

  it('rejects unsafe service and variable names', () => {
    expect(() => toComposeOverrideYaml('auth:\n  x', {})).toThrow()
    expect(() => toComposeOverrideYaml('auth', { 'BAD\nNAME': 'x' })).toThrow()
  })
})

describe('planAuthRuntimeApply', () => {
  it('applies non-secret fields and reports stored secrets as skipped', () => {
    const plan = planAuthRuntimeApply({
      config: { SITE_URL: 'https://x.test', SMTP_PASS: 'leaked', EXTERNAL_GITHUB_ENABLED: true },
      storedSecretFields: ['SMTP_PASS', 'EXTERNAL_GITHUB_SECRET'],
      secretFieldNames: new Set(['SMTP_PASS', 'EXTERNAL_GITHUB_SECRET']),
    })
    expect(plan.appliedFields).toEqual(['EXTERNAL_GITHUB_ENABLED', 'SITE_URL'])
    expect(plan.skippedSecretFields).toEqual(['EXTERNAL_GITHUB_SECRET', 'SMTP_PASS'])
    expect(plan.content).toContain('GOTRUE_EXTERNAL_GITHUB_ENABLED: "true"')
    expect(plan.content).not.toContain('leaked')
    expect(plan.content).not.toContain('SMTP_PASS')
  })
})
