// [self-platform] Delivers stored Edge Function secrets to a Fleet-managed
// stack.
//
// The Edge Runtime main service passes its own environment to every user
// worker, so the secrets become environment variables of the `functions`
// service, sealed to the Fleet Agent: `secrets.compose.yml` in the `functions`
// configuration domain on Compose, or the Secret
// supabase-fleet-functions-secrets on Kubernetes. Fleet then restarts
// `functions`. See service-config-apply.ts for the apply mechanics.
import { isReservedFunctionSecretName, readFunctionSecretValues } from './function-secrets'
import {
  commitServiceConfigApply,
  loadServiceConfigApplyPlan,
  type ApplyRequest,
  type ServiceConfigApplyAvailability,
  type ServiceConfigApplyOperation,
  type ServiceConfigApplyState,
  type ServiceConfigSpec,
} from './service-config-apply'

// The same domain and ownership policy as function deployments.
const FUNCTIONS_SPEC: ServiceConfigSpec = {
  domain: 'functions',
  service: 'functions',
  label: 'Edge Function secrets',
  secretsHeader: '# Generated by Fleet from the project Edge Function secrets. Do not edit.',
  // User secrets never collide with the names the manifests set with `env`,
  // because those names are reserved.
  supportsKubernetes: true,
}

export type FunctionSecretsApplyStatus = {
  availability: ServiceConfigApplyAvailability
  state: ServiceConfigApplyState
  isOwnedByFleet: boolean
  /** Secrets delivered sealed to the Fleet Agent, sorted. */
  sealedSecretNames: string[]
  /** Secrets that cannot be delivered because the Agent has no key, sorted. */
  skippedSecretNames: string[]
  /** Stored before names were checked, and never delivered, sorted. */
  reservedSecretNames: string[]
  expectedGeneration: number
  operation: ServiceConfigApplyOperation | null
}

/** Splits stored secrets into deliverable environment and reserved names. */
export function planFunctionSecretsEnv(secrets: Record<string, string>): {
  env: Record<string, string>
  reservedNames: string[]
} {
  const env: Record<string, string> = {}
  const reservedNames: string[] = []
  for (const [name, value] of Object.entries(secrets)) {
    if (isReservedFunctionSecretName(name)) reservedNames.push(name)
    else env[name] = value
  }
  return { env, reservedNames: reservedNames.sort() }
}

async function loadFunctionSecretsApplyPlan(
  projectRef: string,
  request: ApplyRequest,
  isStrict: boolean
) {
  const { env, reservedNames } = planFunctionSecretsEnv(await readFunctionSecretValues(projectRef))
  const names = Object.keys(env).sort()
  const applyPlan = await loadServiceConfigApplyPlan({
    spec: FUNCTIONS_SPEC,
    projectRef,
    request,
    isStrict,
    plainFiles: [],
    secretsEnv: names.length === 0 ? null : env,
    hasPlainSettings: false,
  })
  const status: FunctionSecretsApplyStatus = {
    availability: applyPlan.availability,
    state: applyPlan.state,
    isOwnedByFleet: applyPlan.isOwnedByFleet,
    sealedSecretNames: applyPlan.areSecretsSealed ? names : [],
    skippedSecretNames: applyPlan.areSecretsSealed ? [] : names,
    reservedSecretNames: reservedNames,
    expectedGeneration: applyPlan.expectedGeneration,
    operation: applyPlan.operation,
  }
  return { applyPlan, status }
}

export async function getFunctionSecretsApplyStatus(
  projectRef: string,
  request: ApplyRequest
): Promise<FunctionSecretsApplyStatus> {
  return (await loadFunctionSecretsApplyPlan(projectRef, request, false)).status
}

export async function applyFunctionSecrets(input: {
  projectRef: string
  expectedGeneration: number
  confirmOwnership: boolean
  idempotencyKey: string
  actor: string
  correlationId: string
  aal?: string
  aalAuthenticatedAt?: number
}) {
  const { applyPlan } = await loadFunctionSecretsApplyPlan(
    input.projectRef,
    { actor: input.actor, correlationId: input.correlationId },
    true
  )
  return commitServiceConfigApply(applyPlan, input)
}
