-- 04-roles.sql — M3.0 role model: roles / role_projects / member_roles.
-- Idempotent: runs on fresh initdb (docker-entrypoint-initdb.d) AND can be
-- applied manually to an existing platform-db (README "Upgrading an existing
-- platform-db data dir"). Re-running is a no-op.

create table if not exists platform.roles (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references platform.organizations(id) on delete cascade,
  base_role_id bigint not null references platform.roles(id),
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, name)
);

create table if not exists platform.role_projects (
  role_id bigint not null references platform.roles(id) on delete cascade,
  project_id bigint not null references platform.projects(id) on delete cascade,
  primary key (role_id, project_id)
);

create table if not exists platform.member_roles (
  profile_id bigint not null references platform.profiles(id) on delete cascade,
  role_id bigint not null references platform.roles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (profile_id, role_id)
);

-- Seed the four base roles for the default organization with fixed ids 1-4.
-- Names MUST match FIXED_ROLE_ORDER in
-- apps/studio/data/organization-members/organization-roles-query.ts.
-- base_role_id = id marks a base role (self-reference).
insert into platform.roles (id, organization_id, base_role_id, name, description)
select v.id, o.id, v.id, v.name, v.description
from (
  values
    (1, 'Owner', 'Full access, including organization management.'),
    (2, 'Administrator', 'Full access except organization management and granting Owner.'),
    (3, 'Developer', 'Project content read/write; no settings, credentials, or member management.'),
    (4, 'Read-only', 'Read-only access to project content.')
) as v (id, name, description)
cross join platform.organizations o
where o.slug = 'default'
on conflict (id) do nothing;

-- Keep the identity sequence past the seeded ids (derived roles start at 5+).
select setval(
  pg_get_serial_sequence('platform.roles', 'id'),
  greatest((select coalesce(max(id), 4) from platform.roles), 4)
);

-- Backfill: every existing member gets Owner (spec §2 decision #8). The join
-- on roles id 1 makes this a no-op if the seed above found no default org.
insert into platform.member_roles (profile_id, role_id)
select om.profile_id, r.id
from platform.organization_members om
join platform.roles r on r.id = 1
on conflict do nothing;
