-- 05-invitations.sql — M3.2 org invitations. Idempotent: runs on fresh initdb
-- (docker-entrypoint-initdb.d) AND can be applied manually to an existing
-- platform-db (README "Upgrading an existing platform-db data dir"). Re-running
-- is a no-op. 04-roles.sql conventions.
create table if not exists platform.invitations (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references platform.organizations(id) on delete cascade,
  invited_email text not null,
  -- Base org-scoped role only (route-enforced, like PATCH member V2). Scoped
  -- grants are created at accept time via the derived-role machinery.
  role_id bigint not null references platform.roles(id),
  -- Project refs (NOT ids): re-validated at accept so a project deleted between
  -- invite and accept fails loud. NULL / empty = org-wide grant on accept.
  role_scoped_projects text[],
  -- Stored for contract fidelity; never enforced (no SSO in self-platform).
  require_sso boolean not null default false,
  -- 122-bit random capability token, non-enumerable, unique.
  token uuid not null default gen_random_uuid() unique,
  invited_by bigint not null references platform.profiles(id),
  invited_at timestamptz not null default now(),
  -- MUST match the UI's isInviteExpired (invited_at + 24h, Organization.utils.ts).
  expires_at timestamptz not null default (now() + interval '24 hours'),
  -- Consumed marker; the row is retained (not deleted) on accept so a re-used
  -- token maps to the "already accepted or declined" screen (401).
  accepted_at timestamptz
);

-- One pending invite per email per org (revoke hard-deletes; accept sets
-- accepted_at, freeing the email for a future re-invite).
create unique index if not exists invitations_org_pending_email_uq
  on platform.invitations (organization_id, invited_email)
  where accepted_at is null;
