#!/usr/bin/env bash
# Git merge driver for apps/studio/**/*.tsx: always take the upstream (theirs)
# version. The wrap is regenerated by sync-upstream.sh afterwards. Translations
# are never here (they live in zh-CN.json), so nothing is lost.
# Args (from .gitattributes): %O %A %B  -> base, ours, theirs
set -euo pipefail
BASE="$1"; OURS="$2"; THEIRS="$3"
cp "$THEIRS" "$OURS"
exit 0
